server:
  host_name: localhost
  port: 8080

database:
  host: localhost
  user: root
  password: password
  name: store
  table: orders
  drop_existing_db: True

cache:
  enable_cache: False
  cache_lifetime: 60
